### ISSUE TITLE
[ADD] Добавить возможность получения данных в xml

### ISSUE THREAD

**Issue by anry-das** [Viencer/NewsApp#6]
Согласно требованиям, необходимо добавить возможность получения данных в xml
Подробнее тут https://stackoverflow.com/questions/33009918/spring-boot-controller-content-negotiation/33010537#33010537 (конфигурацию рекомендую добавить в пакет **config**)
Обрати внимание, что полученные данные сохранять на стороне сервера не нужно (#4 )

**Comment by Viencer** [comment]
Commits on Mar 4, 2020
Исправление мелких ошибок
