### ISSUE TITLE
[SERVICE] Вынести парсинг JSON в конвертер

### ISSUE THREAD

**Issue by anry-das** [Viencer/NewsApp#9]
Для парсинга удобно использовать интерфейс Converter<S,T>
Для испотльзования конвертора нужно имплементировать этот инт-с, зарегестрировать его в конфигурации и использовать DI ConversionService в сервисе NewsService

**Comment by anry-das** [comment]
конвертер лучше поместить в отдельный пакет

**Comment by Viencer** [comment]
можно его поместить в модель?

**Comment by anry-das** [comment]
> 
> 
> можно его поместить в модель?

лучше вынести конвертер в отдельный пакет

**Comment by Viencer** [comment]
№ 9 
Commits on Mar 13, 2020
